### ISSUE TITLE
"Community" Tab changes

### ISSUE THREAD

**Issue by m3rlin94** [SustainableEducationFoundation/LiveSite#12]
1. Community -> People (ex : http://ahlab.org/people)
2. and we should seperate it in to few categories
                      * team
                      *alumni
                       *resources/speakers/mentors  (likewise )
                       * also, advisory panel

**Comment by naveentherocker** [comment]
Please give the list of names under Team, Alumni, Speakers/Mentors and the Advisory Panel

**Comment by m3rlin94** [comment]
@naveentherocker follow the below link machan. https://docs.google.com/document/d/1_sL_kJd6s3r8cHOZ6p3mVpLFt5iCsVnfULuzmAcujkI/edit
