### ISSUE TITLE
Better Image for "Virtual Sessions"

### ISSUE THREAD

**Issue by akshika47** [SustainableEducationFoundation/LiveSite#21]
In the slide show. for the "Virtual Sessions" The image is "me" doing a talk.  We need a better image to what happens in live events.Maybe a screen shot from a live event or a image collage of Live sessions screen shots. Be creative here. 

Maybe also change Virtual sessions to  "Webinars"

**Comment by m3rlin94** [comment]
@akshika47 please add Suresh (Peiris) for the team and assign him. he's re-doing the images

**Comment by m3rlin94** [comment]
DONE!
