### ISSUE TITLE
Changes to Contact Page

### ISSUE THREAD

**Issue by DulanDias** [SustainableEducationFoundation/LiveSite#27]
above the contact form.. provide details such as our email address (so that they can directly reach us), and add our social links too..

otherwise just the contact form looks empty..

**Comment by m3rlin94** [comment]
social links i'm not sure necessary since it's in footer. also, we only have email address to add as a contact detail.

**Comment by DulanDias** [comment]
But we also somehow needs to show the email address to people visiting neh? so that they can get the email address and contact us without using the contact form?

**Comment by m3rlin94** [comment]
added fb feed as you mentioned. will improve in the second iteration
