### ISSUE TITLE
Add Floating Messenger Button

### ISSUE THREAD

**Issue by DulanDias** [SustainableEducationFoundation/LiveSite#32]
On the website, can we have a floating messenger button on the lower right corner that connects to our Facebook Page Inbox?

![image](http://tribeupacademy.com/wp-content/uploads/2016/06/facebook-message-us-button.jpg)

https://tribeupacademy.com/2016/06/17/create-facebook-message-us-button-website/

**Comment by m3rlin94** [comment]
adding our own code can get ugly neh? i'll see if there is a widget already embedded in the theme.

**Comment by m3rlin94** [comment]
Done
