### ISSUE TITLE
Messenger Pop Up Collapsing Error

### ISSUE THREAD

**Issue by DulanDias** [SustainableEducationFoundation/LiveSite#36]
Refer screenshot.
![image](https://user-images.githubusercontent.com/8329996/42422097-f47039f6-82fd-11e8-86ec-996deaeb01d3.png)

This happened when minimizing the pop up by clicking on the Messenger icon.

**Comment by m3rlin94** [comment]
don't have a solution for this at the moment.

**Comment by m3rlin94** [comment]
done
