### ISSUE TITLE
Contribute Page is Not Complete and Not Functioning

### ISSUE THREAD

**Issue by DulanDias** [SustainableEducationFoundation/LiveSite#39]
Cover images are not complete and not appropriate at some places.
Descriptions are not shown properly, and there is no functionality to click and view even.

**Comment by m3rlin94** [comment]
i have asked kasun to design them. current images are for demo only. i'm waiting for the designs

**Comment by m3rlin94** [comment]
Still waiting for designs. other bugs are fixed, so im closing this issue. @DulanDias
