### ISSUE TITLE
About Section of SEF

### ISSUE THREAD

**Issue by akshika47** [SustainableEducationFoundation/LiveSite#43]
In the about section of SEF, we need to what we do and also what we would like to achieve.
So for what we do we could mention the FB live sessions, workshops etc.

under the part what we would like to achieve it should be quantifiable goals. 
Good examples are like 2 million trees goal by Thuru and also 1 million Women to Tech, so these are quantifiable goals. We could have around 2-3 goals which would give us targets to work

**Comment by akshika47** [comment]
This would be a good statistic to improve - http://www.statistics.gov.lk/education/ComputerLiteracy/ComputerLiteracy-2017Q1-Q2-final.pdf

**Comment by jayasanka-sack** [comment]
done
