### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by akshika47** [SustainableEducationFoundation/LiveSite#9]
Please remove the place holders in the footer and edit it

**Comment by bpdesilva** [comment]
Requires UI person to change color and height.

**Comment by bpdesilva** [comment]
Color Light Blue Please my eyes hurt looking at Purple !

**Comment by bpdesilva** [comment]
Social Links to Update them.

**Comment by jayasanka-sack** [comment]
Created new Light Blue color schema.

**Comment by jayasanka-sack** [comment]
@bpdesilva  @tsuresh 
Created two color schemes. (Light Blue & Flat Purple)
check it out
